import sys
import numpy as np

FreeCADpath = [ "/Applications/FreeCAD.app/Contents/Resources/lib/", \
                "/Applications/FreeCAD.app/Contents/Resources/Mod/", \
                "/Applications/FreeCAD.app/Contents/Resources/lib64/", \
                "/Applications/FreeCAD.app/Contents/Resources/lib64/", \
                "/Users/kent/Library/Preferences/FreeCAD/Mod" ]
for path in FreeCADpath:
    sys.path.append( path )
# import FreeCAD
import Part
sys.exit()

# ========================================================= #
# ===  set points / tie / rotate it along zAxis         === #
# ========================================================= #
def points_rotate_along_zAxis( inpFile=None ):
    # ------------------------------------------------- #
    # --- [1] Arguments                             --- #
    # ------------------------------------------------- #
    if ( inpFile is None ): inpFile = sys.exit( "[points_rotate_along_zAxis] inpFile == ??  " )
    pts     = []
    lines   = []
    with open( inpFile, "r" ) as f:
        ptsData = np.loadtxt( f )
    # ------------------------------------------------- #
    # --- [2] generate points / lines               --- #
    # ------------------------------------------------- #
    #  -- [2-1] points                              --  #
    for pt in ptsData:
        pts.append( FreeCAD.Base.Vector( pt[0], pt[1], pt[2] ) )
    #  -- [2-2] lines                               --  #
    for ik in range( len( pts )-1 ):
        lines.append( Part.LineSegment( pts[ik], pts[ik+1]   ) )
    # ------------------------------------------------- #
    # --- [3] rotation                              --- #
    # ------------------------------------------------- #
    S1 = Part.Shape( lines )
    Part.show( V1 )

inpFile = "/Users/kent/freeCAD/pytMacro_test/dat/magSurface1D.dat"
points_rotate_along_zAxis( inpFile=inpFile )
    
# V1 = FreeCAD.Base.Vector(0,0,0)
# V2 = FreeCAD.Base.Vector(0,0,1)
# V3 = FreeCAD.Base.Vector(1,0,1)
# V4 = FreeCAD.Base.Vector(1,0,0)

# L1 = Part.LineSegment(V1,V2)
# L2 = Part.LineSegment(V2,V3)
# L3 = Part.LineSegment(V3,V4)
# L4 = Part.LineSegment(V4,V1)

# S1 = Part.Shape( [L1,L2,L3,L4] )
# W1 = Part.Wire( S1.Edges )
# P1 = W1.extrude( FreeCAD.Base.Vector( 0,1,0 ) )

